run_config:
  name: housing-price-project
  author: Ziqiao Ao, Yucheng Feng, Jiusi Li, Xin Shu
  version: default
  description: House price prediction in Perth (located in Western Australia).
  dependencies: requirements.txt
  output: artifacts





model_tuning:
  random_forest_hyperparameters:
    n_estimators: [100]
    # max_depth: [5, 8]
    # min_samples_split: [2, 5]
    # min_samples_leaf: [2, 5]

  xgboost_hyperparameters:
    learning_rate: [0.01, 0.05, 0.1]
    # max_depth: [3, 5, 7]

  linear_ridge_hyperparameters:
    alpha: [0.1, 1.0, 10.0]

  cv: 2

  verbose: 1

  metrics: ["root_mean_squared_error", "mean_absolute_error", "r2_score"]

  best_model_metric: "root_mean_squared_error"
